# This is a basic workflow to help you get started with Actions

name: push-build-check

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: linux-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: Setup ironment
        uses: actions/setup-go@v3.2.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.22 # optional
      - name: build
        run: |
          go mod tidy
          go run export/main.go
          
          CGO_ENABLED=0
          GOOS="windows"
          GOARCH="386"
          go build -o bin/waym3u8_windows_x86.exe

          GOOS="windows"
          GOARCH="amd64"
          go build -o bin/waym3u8_windows_x64.exe

          GOOS="linux"
          GOARCH="386"
          go build -o bin/waym3u8_linux_x86

          GOOS="linux"
          GOARCH="amd64"
          go build -o bin/waym3u8_linux_x64

          GOOS="linux"
          GOARCH="mipsle"
          go build -o bin/waym3u8_linux_mipsle