# This is a basic workflow to help you get started with Actions

name: release-build-upload

# Controls when the workflow will run
on: 
  release:
    types: [ created ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-upload_windows-x86:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.22 # optional
      - name: build
        run: |
          go mod tidy
          go run export/main.go
          
          $env:CGO_ENABLED=0
          $env:GOOS="windows"
          $env:GOARCH="386"
          go build -o bin/waym3u8_windows_x86.exe

          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -o bin/waym3u8_windows_x64.exe

          $env:GOOS="linux"
          $env:GOARCH="386"
          go build -o bin/waym3u8_linux_x86

          $env:GOOS="linux"
          $env:GOARCH="amd64"
          go build -o bin/waym3u8_linux_x64

          $env:GOOS="linux"
          $env:GOARCH="mipsle"
          go build -o bin/waym3u8_linux_mipsle

      - name: upload release waym3u8_windows_x86
        uses: Guerra24/upload-to-release@v1
        with:
          name: waym3u8_windows_x86-${{ github.ref_name }}.exe
          path: bin/waym3u8_windows_x86.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload release waym3u8_windows_x64
        uses: Guerra24/upload-to-release@v1
        with:
          name: waym3u8_windows_x64-${{ github.ref_name }}.exe
          path: bin/waym3u8_windows_x64.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload release waym3u8_linux_x86
        uses: Guerra24/upload-to-release@v1
        with:
          name: waym3u8_linux_x86-${{ github.ref_name }}.exe
          path: bin/waym3u8_linux_x86
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload release waym3u8_linux_x64
        uses: Guerra24/upload-to-release@v1
        with:
          name: waym3u8_linux_x64-${{ github.ref_name }}.exe
          path: bin/waym3u8_linux_x64
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload release waym3u8_linux_mipsle
        uses: Guerra24/upload-to-release@v1
        with:
          name: waym3u8_linux_mipsle-${{ github.ref_name }}.exe
          path: bin/waym3u8_linux_mipsle
          repo-token: ${{ secrets.GITHUB_TOKEN }}